version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    networks:
      - jelly_network
    env_file:
      - .env.production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  jelly_network:
    driver: bridge
