version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/tecitostore.com/fullchain.pem:/etc/letsencrypt/live/tecitostore.com/fullchain.pem
      - /etc/letsencrypt/live/tecitostore.com/privkey.pem:/etc/letsencrypt/live/tecitostore.com/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    networks:
      - jelly_network
    env_file:
      - .env.production

networks:
  jelly_network:
    driver: bridge
