version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "3001:80"
    networks:
      - jelly_network
    env_file:
      - .env.production

networks:
  jelly_network:
    driver: bridge
