version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - jelly_network
    env_file:
      - .env.production

networks:
  jelly_network:
    driver: bridge
