version: '3.9'

services:
  frontend:
    build:
      context: .
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "3000:80"
    networks:
      - jelly_network

networks:
  jelly_network:
    driver: bridge
