import useCreateProduct from "../../CreateProduct/hooks/useCreateProduct.ts";
import useBooleanValidation from "../../../../../hooks/Commons/useBooleanValidation.ts";

const useEditProduct = () => {

    const {
        value: initialized,
        setValue: setInitialized,
    } = useBooleanValidation('initialized')

    const {
        name,
        setName,
        nameError,
        setNameError,
        description,
        setDescription,
        descriptionError,
        setDescriptionError,
        price,
        setPrice,
        priceError,
        setPriceError,
        stock,
        setStock,
        stockError,
        setStockError,
        endpointError,
        setEndpointError,
        endpointSuccess,
        setEndpointSuccess,
        loading,
        setLoading,
        snackbarOpen,
        setSnackbarOpen,
        focusedInput,
        setFocusedInput,
        category,
        setCategory,
        categoryError,
        setCategoryError,
        group,
        setGroup,
        groupError,
        setGroupError,
    } = useCreateProduct()

    return {
        name,
        setName,
        nameError,
        setNameError,
        description,
        setDescription,
        descriptionError,
        setDescriptionError,
        price,
        setPrice,
        priceError,
        setPriceError,
        stock,
        setStock,
        stockError,
        setStockError,
        endpointError,
        setEndpointError,
        endpointSuccess,
        setEndpointSuccess,
        loading,
        setLoading,
        snackbarOpen,
        setSnackbarOpen,
        focusedInput,
        setFocusedInput,
        category,
        setCategory,
        categoryError,
        setCategoryError,
        group,
        setGroup,
        groupError,
        setGroupError,
        initialized,
        setInitialized,
    }
}

export default useEditProduct;
